import { FileLibraryListItem } from "../../../../types";

export const storiesDefaultFileLibraryList: Array<FileLibraryListItem> = [
  {
    id: 1,
    title: "amet qui sunt",
    description:
      "Deserunt et reprehenderit ut qui ea ex excepteur incididunt velit. Reprehenderit dolor dolor dolore non occaecat cillum aute fugiat ea nisi nostrud. Occaecat velit excepteur non aliquip nulla. Dolor consectetur ullamco consequat sint dolor Lorem dolor. Est laborum laborum esse duis dolor occaecat aliqua esse quis sit nulla qui ad irure. Incididunt excepteur aute mollit voluptate mollit veniam et nostrud deserunt voluptate.\r\n",
    size: 187657,
    fileName: "qui.jpg",
    thumbnailUrl: "https://loremflickr.com/640/360?v=01",
    createdAt: 1208133942801,
    filename: "",
    original_filename: "",
    extension: "",
    thumbnail_path: "",
    path: "",
    module: "",
    mime_type: "",
    file_type: "",
    thumbnail_url: "",
    path_url: "",
  },
  {
    id: 2,
    title: "laboris excepteur voluptate",
    description:
      "Proident ea aliquip ad sit et. Culpa ex qui ad qui proident aliquip veniam dolor deserunt eu nisi consequat esse cupidatat. Qui dolore aliqua magna est labore consectetur non elit. Culpa proident consectetur proident nostrud do sint velit dolor ullamco nisi est pariatur. Ex esse cupidatat tempor dolor quis sunt dolore in in proident eiusmod nisi proident quis. Veniam consectetur reprehenderit quis do dolor proident sint dolor. Ex irure sunt proident sunt.\r\n",
    size: 119197,
    fileName: "cillum.jpg",
    thumbnailUrl: "https://loremflickr.com/640/360?v=02",
    createdAt: 1136027683961,
    filename: "",
    original_filename: "",
    extension: "",
    thumbnail_path: "",
    path: "",
    module: "",
    mime_type: "",
    file_type: "",
    thumbnail_url: "",
    path_url: "",
  },
  {
    id: 5,
    title: "cupidatat ad ex",
    description:
      "Ut nisi et consectetur enim culpa exercitation minim voluptate aute incididunt laborum consectetur consectetur. Sunt ullamco amet laborum nulla ut. Enim pariatur amet incididunt voluptate magna.\r\n",
    size: 171436,
    fileName: "quis.jpg",
    thumbnailUrl: "https://loremflickr.com/640/360?v=03",
    createdAt: 1848445892836,
    filename: "",
    original_filename: "",
    extension: "",
    thumbnail_path: "",
    path: "",
    module: "",
    mime_type: "",
    file_type: "",
    thumbnail_url: "",
    path_url: "",
  },
  {
    id: 4,
    title:
      "consectetur dolore consequatconsectetur dolore consequatconsectetur dolore consequatconsectetur dolore consequatconsectetur dolore consequatconsectetur dolore consequatconsectetur dolore consequatconsectetur dolore consequat",
    description:
      "Laboris amet ipsum commodo in eu in excepteur sint consectetur ullamco irure est dolore. Consectetur quis irure laborum est voluptate qui qui ad minim. Laboris ex adipisicing do eiusmod amet veniam laboris amet quis.\r\n",
    size: 178114,
    fileName: "excepteur.jpg",
    thumbnailUrl: "https://loremflickr.com/640/360?v=04",
    createdAt: 12846175551490,
    
    filename: "",
    original_filename: "",
    extension: "",
    thumbnail_path: "",
    path: "",
    module: "",
    mime_type: "",
    file_type: "",
    thumbnail_url: "",
    path_url: "",
  },

];
